version: '3.8'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    platform: linux/amd64
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL","/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrongPassword123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 20
    volumes: [sql-data:/var/opt/mssql]
    networks: [app-network]

  mongo:
    image: mongo
    container_name: mongo
    ports: ["27017:27017"]
    volumes: [mongo-data:/data/db]
    networks: [app-network]

  server-net:
    build:
      context: ./server-net/
      dockerfile: Dockerfile
    depends_on:
      sql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=ShoppingAppDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true;MultipleActiveResultSets=true"
    ports: ["5177:80"]
    networks: [app-network]

  server-node:
    build:
      context: ./server-node
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
    ports: ["3000:3000"]
    networks: [app-network]

networks:
  app-network:
    driver: bridge

volumes:
  sql-data:
  mongo-data:
