# shopping-client/Dockerfile
FROM node:18

WORKDIR /app
COPY . .
# RUN npm install
# RUN npm run build

# שימוש ב־serve להרצת האפליקציה
RUN npm install -g serve
# CMD ["serve", "-s", "dist", "-l", "5173"]
